name: CommandShop
author: Kepler_
version: 1

description: Buy and sell items anytime, anywhere

main: co.kepler.commandshop.CommandShop

commands:
  shop:
    description: Shop commands
    usage: /shop
    aliases:
    - s
